# Generated by Django 5.2.3 on 2025-11-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airecipe', '0005_alter_wishlistitem_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('storage', models.CharField(choices=[('Room', 'Room'), ('Fridge', 'Fridge'), ('Freezer', 'Freezer')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
