# Generated by Django 5.2.3 on 2025-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airecipe', '0006_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
    ]
